import { PressInfo } from './Grid/GridInterface';
export const press_list: PressInfo[] = [
  {
    id: 1,
    name: 'YTN 사이언스',
    dark_src: `dark/img1.svg`,
    light_src: `light/img1.svg`,
  },
  {
    id: 2,
    name: 'Able뉴스',
    dark_src: 'dark/img2.svg',
    light_src: 'light/img2.svg',
  },
  {
    id: 3,
    name: '뉴스토마토',
    dark_src: 'dark/img3.svg',
    light_src: 'light/img3.svg',
  },
  {
    id: 4,
    name: '데일리한국',
    dark_src: 'dark/img4.svg',
    light_src: 'light/img4.svg',
  },
  {
    id: 5,
    name: '시사오늘',
    dark_src: 'dark/img5.svg',
    light_src: 'light/img5.svg',
  },
  {
    id: 6,
    name: '대전방송',
    dark_src: 'dark/img6.svg',
    light_src: 'light/img6.svg',
  },
  {
    id: 7,
    name: '이코노타임즈',
    dark_src: 'dark/img7.svg',
    light_src: 'light/img7.svg',
  },
  {
    id: 8,
    name: '독서신문',
    dark_src: 'dark/img8.svg',
    light_src: 'light/img8.svg',
  },
  {
    id: 9,
    name: '산',
    dark_src: 'dark/img9.svg',
    light_src: 'light/img9.svg',
  },
  {
    id: 10,
    name: '시사 IN',
    dark_src: 'dark/img10.svg',
    light_src: 'light/img10.svg',
  },
  {
    id: 11,
    name: '한국경제',
    dark_src: 'dark/img11.svg',
    light_src: 'light/img11.svg',
  },
  {
    id: 12,
    name: 'NEWSIS',
    dark_src: 'dark/img12.svg',
    light_src: 'light/img12.svg',
  },
  {
    id: 13,
    name: '동아일보',
    dark_src: 'dark/img13.svg',
    light_src: 'light/img13.svg',
  },
  {
    id: 14,
    name: 'KBS',
    dark_src: 'dark/img14.svg',
    light_src: 'light/img14.svg',
  },
  {
    id: 15,
    name: 'BLOTER',
    dark_src: 'dark/img15.svg',
    light_src: 'light/img15.svg',
  },
  {
    id: 16,
    name: '한국경제TV',
    dark_src: 'dark/img16.svg',
    light_src: 'light/img16.svg',
  },
  {
    id: 17,
    name: '전자신문',
    dark_src: 'dark/img17.svg',
    light_src: 'light/img17.svg',
  },
  {
    id: 18,
    name: '스포츠조선',
    dark_src: 'dark/img18.svg',
    light_src: 'light/img18.svg',
  },
  {
    id: 19,
    name: '서울신문',
    dark_src: 'dark/img19.svg',
    light_src: 'light/img19.svg',
  },
  {
    id: 20,
    name: '중앙일보',
    dark_src: 'dark/img20.svg',
    light_src: 'light/img20.svg',
  },
  {
    id: 21,
    name: '노컷뉴스',
    dark_src: 'dark/img21.svg',
    light_src: 'light/img21.svg',
  },
  {
    id: 22,
    name: '프레시안',
    dark_src: 'dark/img22.svg',
    light_src: 'light/img22.svg',
  },
  {
    id: 23,
    name: 'sportalkorea',
    dark_src: 'dark/img23.svg',
    light_src: 'light/img23.svg',
  },
  {
    id: 24,
    name: '한국일보',
    dark_src: 'dark/img24.svg',
    light_src: 'light/img24.svg',
  },
  {
    id: 25,
    name: '여성경제신문',
    dark_src: 'dark/img25.svg',
    light_src: 'light/img25.svg',
  },
  {
    id: 26,
    name: 'IT조선',
    dark_src: 'dark/img26.svg',
    light_src: 'light/img26.svg',
  },
  {
    id: 27,
    name: '철강금속신문',
    dark_src: 'dark/img27.svg',
    light_src: 'light/img27.svg',
  },
  {
    id: 28,
    name: '정신의학신문',
    dark_src: 'dark/img28.svg',
    light_src: 'light/img28.svg',
  },
  {
    id: 29,
    name: '뉴스포스트',
    dark_src: 'dark/img29.svg',
    light_src: 'light/img29.svg',
  },
  {
    id: 30,
    name: '씨네21',
    dark_src: 'dark/img30.svg',
    light_src: 'light/img30.svg',
  },
  {
    id: 31,
    name: '정책브리핑',
    dark_src: 'dark/img31.svg',
    light_src: 'light/img31.svg',
  },
  {
    id: 32,
    name: '텐아시아',
    dark_src: 'dark/img32.svg',
    light_src: 'light/img32.svg',
  },
  {
    id: 33,
    name: 'MK스포츠',
    dark_src: 'dark/img33.svg',
    light_src: 'light/img33.svg',
  },
  {
    id: 34,
    name: 'MONDE',
    dark_src: 'dark/img34.svg',
    light_src: 'light/img34.svg',
  },
  {
    id: 35,
    name: 'BBS NEWS',
    dark_src: 'dark/img35.svg',
    light_src: 'light/img35.svg',
  },
  {
    id: 36,
    name: '티브이데일리',
    dark_src: 'dark/img36.svg',
    light_src: 'light/img36.svg',
  },
  {
    id: 37,
    name: 'TV Report',
    dark_src: 'dark/img37.svg',
    light_src: 'light/img37.svg',
  },
  {
    id: 38,
    name: 'Forbes',
    dark_src: 'dark/img38.svg',
    light_src: 'light/img38.svg',
  },
  {
    id: 39,
    name: '주간경향',
    dark_src: 'dark/img39.svg',
    light_src: 'light/img39.svg',
  },
  {
    id: 40,
    name: '비즈한국',
    dark_src: 'dark/img40.svg',
    light_src: 'light/img40.svg',
  },
  {
    id: 41,
    name: 'metro',
    dark_src: 'dark/img41.svg',
    light_src: 'light/img41.svg',
  },
  {
    id: 42,
    name: 'JTBC',
    dark_src: 'dark/img42.svg',
    light_src: 'light/img42.svg',
  },
  {
    id: 43,
    name: '조선Biz',
    dark_src: 'dark/img43.svg',
    light_src: 'light/img43.svg',
  },
  {
    id: 44,
    name: '한겨레',
    dark_src: 'dark/img44.svg',
    light_src: 'light/img44.svg',
  },
  {
    id: 45,
    name: '연합뉴스TV',
    dark_src: 'dark/img45.svg',
    light_src: 'light/img45.svg',
  },
  {
    id: 46,
    name: '미디어오늘',
    dark_src: 'dark/img46.svg',
    light_src: 'light/img46.svg',
  },
  {
    id: 47,
    name: '디지털타임스',
    dark_src: 'dark/img47.svg',
    light_src: 'light/img47.svg',
  },
  {
    id: 48,
    name: 'OSEN',
    dark_src: 'dark/img48.svg',
    light_src: 'light/img48.svg',
  },
  {
    id: 49,
    name: '소년한국일보',
    dark_src: 'dark/img49.svg',
    light_src: 'light/img49.svg',
  },
  {
    id: 50,
    name: 'OBS',
    dark_src: 'dark/img50.svg',
    light_src: 'light/img50.svg',
  },
  {
    id: 51,
    name: '맥스무비',
    dark_src: 'dark/img51.svg',
    light_src: 'light/img51.svg',
  },
  {
    id: 52,
    name: '엑스포츠뉴스',
    dark_src: 'dark/img52.svg',
    light_src: 'light/img52.svg',
  },
  {
    id: 53,
    name: '서울파이낸스',
    dark_src: 'dark/img53.svg',
    light_src: 'light/img53.svg',
  },
  {
    id: 54,
    name: '한국대학신문',
    dark_src: 'dark/img54.svg',
    light_src: 'light/img54.svg',
  },
  {
    id: 55,
    name: 'datanews',
    dark_src: 'dark/img55.svg',
    light_src: 'light/img55.svg',
  },
  {
    id: 56,
    name: 'DigitalToday',
    dark_src: 'dark/img56.svg',
    light_src: 'light/img56.svg',
  },
  {
    id: 57,
    name: '시사위크',
    dark_src: 'dark/img57.svg',
    light_src: 'light/img57.svg',
  },
  {
    id: 58,
    name: 'YTN',
    dark_src: 'dark/img58.svg',
    light_src: 'light/img58.svg',
  },
  {
    id: 59,
    name: 'MBN',
    dark_src: 'dark/img59.svg',
    light_src: 'light/img59.svg',
  },
  {
    id: 60,
    name: '매일경제',
    dark_src: 'dark/img60.svg',
    light_src: 'light/img60.svg',
  },
  {
    id: 61,
    name: '오마이뉴스',
    dark_src: 'dark/img61.svg',
    light_src: 'light/img61.svg',
  },
  {
    id: 62,
    name: 'SBS',
    dark_src: 'dark/img62.svg',
    light_src: 'light/img62.svg',
  },
  {
    id: 63,
    name: '머니투데이',
    dark_src: 'dark/img63.svg',
    light_src: 'light/img63.svg',
  },
  {
    id: 64,
    name: '마이데일리',
    dark_src: 'dark/img64.svg',
    light_src: 'light/img64.svg',
  },
  {
    id: 65,
    name: 'ZDNET Korea',
    dark_src: 'dark/img65.svg',
    light_src: 'light/img65.svg',
  },
  {
    id: 66,
    name: '경향신문',
    dark_src: 'dark/img66.svg',
    light_src: 'light/img66.svg',
  },
  {
    id: 67,
    name: '일간스포츠',
    dark_src: 'dark/img67.svg',
    light_src: 'light/img67.svg',
  },
  {
    id: 68,
    name: '국민일보',
    dark_src: 'dark/img68.svg',
    light_src: 'light/img68.svg',
  },
  {
    id: 69,
    name: '뉴데일리',
    dark_src: 'dark/img69.svg',
    light_src: 'light/img69.svg',
  },
  {
    id: 70,
    name: '뉴스타파',
    dark_src: 'dark/img70.svg',
    light_src: 'light/img70.svg',
  },
];
